### ISSUE TITLE
Uses one cache per worker in starman environment

### ISSUE THREAD

**Issue by accursedm0** [robrwo/Plack-Middleware-Greylist-#7]
Each starman worker seems to get it's own cache instance. 
Could fix it by setting `init_file => 0` but am not sure if there are any downsides to this.

```
my $cache = Cache::FastMmap->new(
  share_file  => "$file",
  init_file   => 0, # must be 0 or each worker will get its own cache  
  unlink_on_exit => 1, # must be 1 so that cache is cleared on restart psgi server
  serializer  => '',
  expire_time => ONE_MINUTE
);
```

**Comment by robrwo** [comment]
Thanks for reporting this.

What happens is that each worker will reset the file, but then they should be using the same file (unless you changed the file definition to use the PID or something else that depends on the workers).  In general we don't care about preserving the data between runs, especially since the data is only good for 60 seconds.

(Where I am using it, each worker is clearly using the same data, since the logger includes the worker PID in log messages when it logs about rate limits.)

Have you been able to verify that each worker is using a distinct instance of the cache?

**Comment by accursedm0** [comment]
Thank you for the quick response.

Yes, it looks very much like each worker uses it's own in memory version of the cache. 
For instance, with number of workers = 5 and default_rate = 10 the limit was reached consistently after exactly 50 calls. 
By checking the log messages I could confirm that the number of hits increased every 6th call only.

I'm not aware that I'm doing something worker related with the file definition:

```
my $app = builder {

  enable "Plack::Middleware::Greylist",
    file         => $root_dir . '/temp/limiter_cache',
    default_rate => 30;
```
Are you also using starman in your case?

**Comment by robrwo** [comment]
Yes, we are using starman. However, we are running it with the `--preload-app` option.

Have you verified that changing init_file to 0 will fix your issue? (I think it will be best to make this an option since not everyone can use the preloading option in Starman etc.)

**Comment by robrwo** [comment]
See https://metacpan.org/release/RRWO/Plack-Middleware-Greylist-v0.5.4-TRIAL as it changes the default to false now.

**Comment by robrwo** [comment]
Let me know if that fixes your issues here and #6

**Comment by accursedm0** [comment]
Yes, this does seem to fix the issue by setting `init_file = 0` . Thank you very much!

Regarding starman, the `--preload-app` option is making the difference indeed but we could not use it. 
It makes perfect sense now though.

**Comment by robrwo** [comment]
Thanks for catching this
